### ISSUE TITLE
Default stack launch causing error

### ISSUE THREAD

**Issue by jinyang7** [awslabs/live-streaming-with-automated-multi-language-subtitling#16]
I am launching the default stack , I have tried URL_PULL and RTMP_PULL and in both cases getting following error which ultimately shuts down enter stack with error ROLLBACK_IN_PROGRESS. Note that I have tried it with the default sample stream or my own rtmp source

00:54:57 Request::Create Resource:: MediaLiveInput
00:54:57 Creating::URL_PULL Input
00:54:57 Exception: An error occurred (BadRequestException) when calling the CreateInput operation: Invalid URL () specified for inputSource

**Comment by EddieGoynesAmazon** [comment]
Hi jinyang. I see you are having a problem. That error **"CreateInput operation: Invalid URL () specified for inputSource"** happens when the MediaLive channel is not able to understand the input URL for some reason. I would try the following. 

Launch the CloudFormation and leave default settings for the input **Source Input Type** to URL_PULL and leave the default HLS CloudFront HLS source populated. Then after you have launched the CloudFormation you are able to stop the MediaLive, and change the input from the AWS MediaLive console. That should guarantee success for you. 

-Erlich Bachman

**Comment by jinyang7** [comment]
Thanks ! Actually I had a wrong coded in there. Changing it fixed my issue,

**Comment by EddieGoynesAmazon** [comment]
Great to hear! 😊
