### ISSUE TITLE
Uploading live captions to own database

### ISSUE THREAD

**Issue by jinyang7** [awslabs/live-streaming-with-automated-multi-language-subtitling#17]
We want to generate captions for existing hls stream from our cdn, what will be best workflow to skip url_pull ? 

Also Is there any way to change the output of vtt captions to be updated to an external database / api ? I assume that will require changing the lamda python code ?

Basically we want to keep using our own cdn stream and just use live captions generated by aws with it.

**Comment by EddieGoynesAmazon** [comment]
Hello. Currently this solution is using AWS Media Live, and AWS Media Package. The Lambda code would have to be changed. But you could have the Lambda code write to a database instead of the code doing a PUT request of the VTT captions into the AWS Media Package http endpoint. You can Fork this repo. 

Thanks. Hope that answers question.
