### ISSUE TITLE
Streaming time limit?

### ISSUE THREAD

**Issue by taschmidt** [awslabs/live-streaming-with-automated-multi-language-subtitling#32]
Hey there, we started looking at this solution to provide captions for our live streaming video. One question though just skimming the code, it looks like you open a single stream [here](https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/master/source/transcribedocker/transcribe-to-dynamo-withSDK.js#L106-L114) so it would therefore be subject to the 4 hour time limit specified [here](https://aws.amazon.com/transcribe/faqs/), correct?

If so, I would be curious to hear your opinion on what other options we might have. Could the code possibly keep track of the total stream time and when approaching 4 hours maybe close and reopen the Transcribe connection?

Thanks,
tim

**Comment by eggoynes** [comment]
Hi there. The time limit can change on the service side, it used to be 2 hours, but now like you mention is 4 hours. Instead of keeping track of the time that the program runs this program will catch the exception after 4 hours, and exit the program. But the container that runs this program runs this program in a loop, so after 4 hours of time the run.sh script keeps it running. So if either FFMPEG or Node.js runs into a problem it will restart it. 👍 

https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/f1e367249e78cf335cfd5df8856e516328edbcb9/source/transcribedocker/run.sh#L6

Here is the try, catch, finally logic. 
https://github.com/awslabs/live-streaming-with-automated-multi-language-subtitling/blob/f1e367249e78cf335cfd5df8856e516328edbcb9/source/transcribedocker/transcribe-to-dynamo-withSDK.js#L72
